spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/movieservice
        username: pjwstk
        password: Pa$$word
    jpa:
        hibernate:
            ddl-auto: validate
